Addon
wrtnio/connectors pull request #45
Opened 2024-06-10 14:52 UTC by hakjje

디스코드 추가 api 까지 구현되었습니다.

2024-06-10 23:26 UTC, kakasoo requested changes
이제보니 discord도 input output DTO가 정의되어 있지 않네요.
이 상태로는 코드가 돌아가질 않습니다.
다시 커밋해주세요.

2024-06-10 23:26 UTC, kakasoo commented on src/controllers/connector/naver/NaverController.ts
> +   */
구글 스프레드시트에는 `블로그 검색 결과 조회 API` 라고 되어 있는데 혹시 따로 설명을 들은 게 있었나요?
제가 생각한 구현체와 실제 구현해주신 내용이 상이하여 질문드립니다.

2024-06-10 23:26 UTC, kakasoo commented on src/providers/connector/naver/NaverProvider.ts
> +  }
만약 상세 페이지를 조회하는 기능이 있다고 한들,
네이버에서 제공하는 API를 사용해야지 크롤링을 해서 css, script가 포함된 html을 넘기는 건 곤란합니다.

2024-06-10 23:26 UTC, kakasoo commented on src/controllers/connector/naver/NaverController.ts
> +  ): Promise<INaver.INaverBlogOutput> {
그리고 `INaverBlogInput`, `INaverBlogOutput` 타입이 커밋이 안되어 있는 거 같습니다.
파일을 찾을 수가 없네요.

2024-06-10 23:45 UTC, kakasoo requested changes
discord 쪽도 리뷰 끝났습니다.
타입들 전부 다 수정이 이루어진 다음에 env 넣고 테스트 돌려보도록 하겠습니다.
감사합니다.

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/naver/INaver.ts
> +    blogUrl: string & Placeholder<"https://blog.naver.com/xxxx">;
typia tags로 URL 형식을 지정해주세요.

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/discord/IDiscord.ts
> +  }
전부 다 어떤 의미인지 작성해주셔야 합니다.
그리고 boolean 타입의 경우에는 기본 값이 있을 텐데 Default 타입 명시해주세요.
숫자 문자열 타입의 경우에는 `'${number}'` 형식으로 작성해주세요.

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/discord/IDiscord.ts
> +  }
`JSDoc` 형태로 전부 수정 부탁드립니다.

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/naver/INaver.ts
> +     * @title 꼭 들어가야하는 키워드
키워드라고 되어 있지만 URL 이므로 타이틀이 서로 뒤바뀐 거 같습니다.
title에 혼동이 없게끔 주소임을 명시해주세요. ( 아래에 코멘트 달겠지만 타입으로도 명시해야 합니다. )

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/discord/IDiscord.ts
> +    flags: number; // 채널 플래그
플래그라면 분명 enum 타입일 거 같습니다.
확인 후에 의미대로 상수 값들을 `Constant` 타입으로 작성해주세요.

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/discord/IDiscord.ts
> +  export interface IDiscordGetChannelOutput {
내부 프로퍼티가 전부 필요한 것인지 체크하여 옵셔널한 것들은 `?:`로 표시해주세요.

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/discord/IDiscord.ts
> +  }
동일 리뷰 드립니다.

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/discord/IDiscord.ts
> +    accent_color: string | null;
한 가지 프로퍼티만 체크했는데 null 과 undefined는 구별해주셔야 합니다.
discord 문서를 확인하니 optional하다고 되어 있지 null이 나온다고는 안 되어 있습니다.

- https://discord.com/developers/docs/resources/user#user-object

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/discord/IDiscord.ts
> +  }
동일 리뷰 드립니다.

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/discord/IDiscord.ts
> +    mentions: any[];
any 타입 사용 금지

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/discord/IDiscord.ts
> +    mention_roles: any[];
any 타입 사용 금지

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/discord/IDiscord.ts
> +    avatar_decoration_data: any | null;
any 타입 사용 금지

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/discord/IDiscord.ts
> +  export interface IDiscordDirectMessageOutput {
이 타입 내부의 any도 모두 지우고 전부 다 명시해주세요.

2024-06-10 23:45 UTC, kakasoo commented on src/api/structures/connector/discord/IDiscord.ts
> +    edited_timestamp: string | null;
시간 값도 typia tags에서 Format을 지정해주셔야 합니다.

2024-06-10 23:55 UTC, kakasoo commented on src/controllers/connector/discord/DiscordController.ts
> +  @core.TypedRoute.Post("/user/find-user-by-id")
`TypedParam`으로 쓰고 find-user-by-id 대신 user/:id로 바꿔주세요.

2024-06-11 00:16 UTC, hakjje commented on src/controllers/connector/naver/NaverController.ts
> +   */
블로그 검색 api 가 구글 시프레드시트에 작성되어 있더라구요
저희는 먼저 그 문서를 기반으로 개발을 진행했는데요
포팅하려고 보니 리튼코드랑 같은 상황이라 1번2번 보류.
3번은 api 가 따로 존재하지 않아서 PM 분께 여쭤보니 없으면 스크랩으로 진행하라고 하셔서 
진행했습니다
혹 변경되어야한다면 말씀해주세요.
아래 내용까지 답변입니다

2024-06-11 00:17 UTC, hakjje commented on src/api/structures/connector/naver/INaver.ts
> +    blogUrl: string & Placeholder<"https://blog.naver.com/xxxx">;
이부분은 위 답변에 따라 진행하겠습니다.

2024-06-11 00:22 UTC, kakasoo commented on src/controllers/connector/naver/NaverController.ts
> +   */
그렇군요. 이 건은 PM에게 확인 후에 답변드리겠습니다.

2024-06-14 06:15 UTC, closed without merging